package entity.document;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AtrTypeSelectionValue generated by hbm2java
 */
@Entity
@Table(name = "atr_type_selection_value", schema = "public")
public class AtrTypeSelectionValue implements java.io.Serializable {

	private BigDecimal atrTypeSelectionValue;
	private BigDecimal docAttributeTypeFk;
	private String valueText;
	private BigDecimal orderby;

	public AtrTypeSelectionValue() {
	}

	public AtrTypeSelectionValue(BigDecimal atrTypeSelectionValue) {
		this.atrTypeSelectionValue = atrTypeSelectionValue;
	}

	public AtrTypeSelectionValue(BigDecimal atrTypeSelectionValue, BigDecimal docAttributeTypeFk, String valueText, BigDecimal orderby) {
		this.atrTypeSelectionValue = atrTypeSelectionValue;
		this.docAttributeTypeFk = docAttributeTypeFk;
		this.valueText = valueText;
		this.orderby = orderby;
	}

	@Id
	@Column(name = "atr_type_selection_value", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getAtrTypeSelectionValue() {
		return this.atrTypeSelectionValue;
	}

	public void setAtrTypeSelectionValue(BigDecimal atrTypeSelectionValue) {
		this.atrTypeSelectionValue = atrTypeSelectionValue;
	}

	@Column(name = "doc_attribute_type_fk", precision = 10, scale = 0)
	public BigDecimal getDocAttributeTypeFk() {
		return this.docAttributeTypeFk;
	}

	public void setDocAttributeTypeFk(BigDecimal docAttributeTypeFk) {
		this.docAttributeTypeFk = docAttributeTypeFk;
	}

	@Column(name = "value_text")
	public String getValueText() {
		return this.valueText;
	}

	public void setValueText(String valueText) {
		this.valueText = valueText;
	}

	@Column(name = "orderby", precision = 10, scale = 0)
	public BigDecimal getOrderby() {
		return this.orderby;
	}

	public void setOrderby(BigDecimal orderby) {
		this.orderby = orderby;
	}

}
