package entity.document;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DataType generated by hbm2java
 */
@Entity
@Table(name = "data_type", schema = "public")
public class DataType implements java.io.Serializable {

	private BigDecimal dataType;
	private String typeName;

	public DataType() {
	}

	public DataType(BigDecimal dataType) {
		this.dataType = dataType;
	}

	public DataType(BigDecimal dataType, String typeName) {
		this.dataType = dataType;
		this.typeName = typeName;
	}

	@Id
	@Column(name = "data_type", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getDataType() {
		return this.dataType;
	}

	public void setDataType(BigDecimal dataType) {
		this.dataType = dataType;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
