package entity.document;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocAttribute generated by hbm2java
 */
@Entity
@Table(name = "doc_attribute", schema = "public")
public class DocAttribute implements java.io.Serializable {

	private BigDecimal docAttribute;
	private BigDecimal atrTypeSelectionValueFk;
	private BigDecimal docAttributeTypeFk;
	private BigDecimal documentFk;
	private String typeName;
	private String valueText;
	private BigDecimal valueNumber;
	private Date valueDate;
	private BigDecimal dataType;
	private BigDecimal orderby;
	private String required;

	public DocAttribute() {
	}

	public DocAttribute(BigDecimal docAttribute) {
		this.docAttribute = docAttribute;
	}

	public DocAttribute(BigDecimal docAttribute, BigDecimal atrTypeSelectionValueFk, BigDecimal docAttributeTypeFk, BigDecimal documentFk, String typeName, String valueText, BigDecimal valueNumber,
			Date valueDate, BigDecimal dataType, BigDecimal orderby, String required) {
		this.docAttribute = docAttribute;
		this.atrTypeSelectionValueFk = atrTypeSelectionValueFk;
		this.docAttributeTypeFk = docAttributeTypeFk;
		this.documentFk = documentFk;
		this.typeName = typeName;
		this.valueText = valueText;
		this.valueNumber = valueNumber;
		this.valueDate = valueDate;
		this.dataType = dataType;
		this.orderby = orderby;
		this.required = required;
	}

	@Id
	@Column(name = "doc_attribute", unique = true, nullable = false, precision = 10, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public BigDecimal getDocAttribute() {
		return this.docAttribute;
	}

	public void setDocAttribute(BigDecimal docAttribute) {
		this.docAttribute = docAttribute;
	}

	@Column(name = "atr_type_selection_value_fk", precision = 10, scale = 0)
	public BigDecimal getAtrTypeSelectionValueFk() {
		return this.atrTypeSelectionValueFk;
	}

	public void setAtrTypeSelectionValueFk(BigDecimal atrTypeSelectionValueFk) {
		this.atrTypeSelectionValueFk = atrTypeSelectionValueFk;
	}

	@Column(name = "doc_attribute_type_fk", precision = 10, scale = 0)
	public BigDecimal getDocAttributeTypeFk() {
		return this.docAttributeTypeFk;
	}

	public void setDocAttributeTypeFk(BigDecimal docAttributeTypeFk) {
		this.docAttributeTypeFk = docAttributeTypeFk;
	}

	@Column(name = "document_fk", precision = 10, scale = 0)
	public BigDecimal getDocumentFk() {
		return this.documentFk;
	}

	public void setDocumentFk(BigDecimal documentFk) {
		this.documentFk = documentFk;
	}

	@Column(name = "type_name")
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "value_text")
	public String getValueText() {
		return this.valueText;
	}

	public void setValueText(String valueText) {
		this.valueText = valueText;
	}

	@Column(name = "value_number", precision = 131089, scale = 0)
	public BigDecimal getValueNumber() {
		return this.valueNumber;
	}

	public void setValueNumber(BigDecimal valueNumber) {
		this.valueNumber = valueNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "value_date", length = 13)
	public Date getValueDate() {
		return this.valueDate;
	}

	public void setValueDate(Date valueDate) {
		this.valueDate = valueDate;
	}

	@Column(name = "data_type", precision = 1, scale = 0)
	public BigDecimal getDataType() {
		return this.dataType;
	}

	public void setDataType(BigDecimal dataType) {
		this.dataType = dataType;
	}

	@Column(name = "orderby", precision = 10, scale = 0)
	public BigDecimal getOrderby() {
		return this.orderby;
	}

	public void setOrderby(BigDecimal orderby) {
		this.orderby = orderby;
	}

	@Column(name = "required", length = 1)
	public String getRequired() {
		return this.required;
	}

	public void setRequired(String required) {
		this.required = required;
	}

	@Override
	public String toString() {
		return "DocAttribute [docAttribute=" + docAttribute + ", atrTypeSelectionValueFk=" + atrTypeSelectionValueFk + ", docAttributeTypeFk=" + docAttributeTypeFk + ", documentFk=" + documentFk
				+ ", typeName=" + typeName + ", valueText=" + valueText + ", valueNumber=" + valueNumber + ", valueDate=" + valueDate + ", dataType=" + dataType + ", orderby=" + orderby
				+ ", required=" + required + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((atrTypeSelectionValueFk == null) ? 0 : atrTypeSelectionValueFk.hashCode());
		result = prime * result + ((dataType == null) ? 0 : dataType.hashCode());
		result = prime * result + ((docAttribute == null) ? 0 : docAttribute.hashCode());
		result = prime * result + ((docAttributeTypeFk == null) ? 0 : docAttributeTypeFk.hashCode());
		result = prime * result + ((documentFk == null) ? 0 : documentFk.hashCode());
		result = prime * result + ((orderby == null) ? 0 : orderby.hashCode());
		result = prime * result + ((required == null) ? 0 : required.hashCode());
		result = prime * result + ((typeName == null) ? 0 : typeName.hashCode());
		result = prime * result + ((valueDate == null) ? 0 : valueDate.hashCode());
		result = prime * result + ((valueNumber == null) ? 0 : valueNumber.hashCode());
		result = prime * result + ((valueText == null) ? 0 : valueText.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DocAttribute other = (DocAttribute) obj;
		if (atrTypeSelectionValueFk == null) {
			if (other.atrTypeSelectionValueFk != null)
				return false;
		} else if (!atrTypeSelectionValueFk.equals(other.atrTypeSelectionValueFk))
			return false;
		if (dataType == null) {
			if (other.dataType != null)
				return false;
		} else if (!dataType.equals(other.dataType))
			return false;
		if (docAttribute == null) {
			if (other.docAttribute != null)
				return false;
		} else if (!docAttribute.equals(other.docAttribute))
			return false;
		if (docAttributeTypeFk == null) {
			if (other.docAttributeTypeFk != null)
				return false;
		} else if (!docAttributeTypeFk.equals(other.docAttributeTypeFk))
			return false;
		if (documentFk == null) {
			if (other.documentFk != null)
				return false;
		} else if (!documentFk.equals(other.documentFk))
			return false;
		if (orderby == null) {
			if (other.orderby != null)
				return false;
		} else if (!orderby.equals(other.orderby))
			return false;
		if (required == null) {
			if (other.required != null)
				return false;
		} else if (!required.equals(other.required))
			return false;
		if (typeName == null) {
			if (other.typeName != null)
				return false;
		} else if (!typeName.equals(other.typeName))
			return false;
		if (valueDate == null) {
			if (other.valueDate != null)
				return false;
		} else if (!valueDate.equals(other.valueDate))
			return false;
		if (valueNumber == null) {
			if (other.valueNumber != null)
				return false;
		} else if (!valueNumber.equals(other.valueNumber))
			return false;
		if (valueText == null) {
			if (other.valueText != null)
				return false;
		} else if (!valueText.equals(other.valueText))
			return false;
		return true;
	}

}
