package entity.document;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocSubjectRelationType generated by hbm2java
 */
@Entity
@Table(name = "doc_subject_relation_type", schema = "public")
public class DocSubjectRelationType implements java.io.Serializable {

	private BigDecimal docSubjectRelationType;
	private String typeName;

	public DocSubjectRelationType() {
	}

	public DocSubjectRelationType(BigDecimal docSubjectRelationType) {
		this.docSubjectRelationType = docSubjectRelationType;
	}

	public DocSubjectRelationType(BigDecimal docSubjectRelationType, String typeName) {
		this.docSubjectRelationType = docSubjectRelationType;
		this.typeName = typeName;
	}

	@Id
	@Column(name = "doc_subject_relation_type", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getDocSubjectRelationType() {
		return this.docSubjectRelationType;
	}

	public void setDocSubjectRelationType(BigDecimal docSubjectRelationType) {
		this.docSubjectRelationType = docSubjectRelationType;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
