package entity.document;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocSubjectType generated by hbm2java
 */
@Entity
@Table(name = "doc_subject_type", schema = "public")
public class DocSubjectType implements java.io.Serializable {

	private BigDecimal docSubjectType;
	private String typeName;

	public DocSubjectType() {
	}

	public DocSubjectType(BigDecimal docSubjectType) {
		this.docSubjectType = docSubjectType;
	}

	public DocSubjectType(BigDecimal docSubjectType, String typeName) {
		this.docSubjectType = docSubjectType;
		this.typeName = typeName;
	}

	@Id
	@Column(name = "doc_subject_type", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getDocSubjectType() {
		return this.docSubjectType;
	}

	public void setDocSubjectType(BigDecimal docSubjectType) {
		this.docSubjectType = docSubjectType;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
