package entity.document;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocSubject generated by hbm2java
 */
@Entity
@Table(name = "doc_subject", schema = "public")
public class DocSubject implements java.io.Serializable {

	private BigDecimal docSubject;
	private BigDecimal docSubjectRelationTypeFk;
	private BigDecimal docSubjectTypeFk;
	private BigDecimal documentFk;
	private BigDecimal subjectFk;
	private String note;

	public DocSubject() {
	}

	public DocSubject(BigDecimal docSubject) {
		this.docSubject = docSubject;
	}

	public DocSubject(BigDecimal docSubject, BigDecimal docSubjectRelationTypeFk, BigDecimal docSubjectTypeFk, BigDecimal documentFk, BigDecimal subjectFk, String note) {
		this.docSubject = docSubject;
		this.docSubjectRelationTypeFk = docSubjectRelationTypeFk;
		this.docSubjectTypeFk = docSubjectTypeFk;
		this.documentFk = documentFk;
		this.subjectFk = subjectFk;
		this.note = note;
	}

	@Id
	@Column(name = "doc_subject", unique = true, nullable = false, precision = 10, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public BigDecimal getDocSubject() {
		return this.docSubject;
	}

	public void setDocSubject(BigDecimal docSubject) {
		this.docSubject = docSubject;
	}

	@Column(name = "doc_subject_relation_type_fk", precision = 10, scale = 0)
	public BigDecimal getDocSubjectRelationTypeFk() {
		return this.docSubjectRelationTypeFk;
	}

	public void setDocSubjectRelationTypeFk(BigDecimal docSubjectRelationTypeFk) {
		this.docSubjectRelationTypeFk = docSubjectRelationTypeFk;
	}

	@Column(name = "doc_subject_type_fk", precision = 10, scale = 0)
	public BigDecimal getDocSubjectTypeFk() {
		return this.docSubjectTypeFk;
	}

	public void setDocSubjectTypeFk(BigDecimal docSubjectTypeFk) {
		this.docSubjectTypeFk = docSubjectTypeFk;
	}

	@Column(name = "document_fk", precision = 10, scale = 0)
	public BigDecimal getDocumentFk() {
		return this.documentFk;
	}

	public void setDocumentFk(BigDecimal documentFk) {
		this.documentFk = documentFk;
	}

	@Column(name = "subject_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectFk() {
		return this.subjectFk;
	}

	public void setSubjectFk(BigDecimal subjectFk) {
		this.subjectFk = subjectFk;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
