package entity.document;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocType generated by hbm2java
 */
@Entity
@Table(name = "doc_type", schema = "public")
public class DocType implements java.io.Serializable {

	private BigDecimal docType;
	private BigDecimal superTypeFk;
	private BigDecimal level;
	private String typeName;

	public DocType() {
	}

	public DocType(BigDecimal docType) {
		this.docType = docType;
	}

	public DocType(BigDecimal docType, BigDecimal superTypeFk, BigDecimal level, String typeName) {
		this.docType = docType;
		this.superTypeFk = superTypeFk;
		this.level = level;
		this.typeName = typeName;
	}

	@Id
	@Column(name = "doc_type", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getDocType() {
		return this.docType;
	}

	public void setDocType(BigDecimal docType) {
		this.docType = docType;
	}

	@Column(name = "super_type_fk", precision = 10, scale = 0)
	public BigDecimal getSuperTypeFk() {
		return this.superTypeFk;
	}

	public void setSuperTypeFk(BigDecimal superTypeFk) {
		this.superTypeFk = superTypeFk;
	}

	@Column(name = "level", precision = 10, scale = 0)
	public BigDecimal getLevel() {
		return this.level;
	}

	public void setLevel(BigDecimal level) {
		this.level = level;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((docType == null) ? 0 : docType.hashCode());
		result = prime * result + ((level == null) ? 0 : level.hashCode());
		result = prime * result + ((superTypeFk == null) ? 0 : superTypeFk.hashCode());
		result = prime * result + ((typeName == null) ? 0 : typeName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DocType other = (DocType) obj;
		if (docType == null) {
			if (other.docType != null)
				return false;
		} else if (!docType.equals(other.docType))
			return false;
		if (level == null) {
			if (other.level != null)
				return false;
		} else if (!level.equals(other.level))
			return false;
		if (superTypeFk == null) {
			if (other.superTypeFk != null)
				return false;
		} else if (!superTypeFk.equals(other.superTypeFk))
			return false;
		if (typeName == null) {
			if (other.typeName != null)
				return false;
		} else if (!typeName.equals(other.typeName))
			return false;
		return true;
	}

}
