package entity.document;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocTypeAttribute generated by hbm2java
 */
@Entity
@Table(name = "doc_type_attribute", schema = "public")
public class DocTypeAttribute implements java.io.Serializable {

	private BigDecimal docTypeAttribute;
	private BigDecimal docAttributeTypeFk;
	private BigDecimal docTypeFk;
	private BigDecimal orderby;
	private String required;
	private String createdByDefault;

	public DocTypeAttribute() {
	}

	public DocTypeAttribute(BigDecimal docTypeAttribute) {
		this.docTypeAttribute = docTypeAttribute;
	}

	public DocTypeAttribute(BigDecimal docTypeAttribute, BigDecimal docAttributeTypeFk, BigDecimal docTypeFk, BigDecimal orderby, String required, String createdByDefault) {
		this.docTypeAttribute = docTypeAttribute;
		this.docAttributeTypeFk = docAttributeTypeFk;
		this.docTypeFk = docTypeFk;
		this.orderby = orderby;
		this.required = required;
		this.createdByDefault = createdByDefault;
	}

	@Id
	@Column(name = "doc_type_attribute", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getDocTypeAttribute() {
		return this.docTypeAttribute;
	}

	public void setDocTypeAttribute(BigDecimal docTypeAttribute) {
		this.docTypeAttribute = docTypeAttribute;
	}

	@Column(name = "doc_attribute_type_fk", precision = 10, scale = 0)
	public BigDecimal getDocAttributeTypeFk() {
		return this.docAttributeTypeFk;
	}

	public void setDocAttributeTypeFk(BigDecimal docAttributeTypeFk) {
		this.docAttributeTypeFk = docAttributeTypeFk;
	}

	@Column(name = "doc_type_fk", precision = 10, scale = 0)
	public BigDecimal getDocTypeFk() {
		return this.docTypeFk;
	}

	public void setDocTypeFk(BigDecimal docTypeFk) {
		this.docTypeFk = docTypeFk;
	}

	@Column(name = "orderby", precision = 10, scale = 0)
	public BigDecimal getOrderby() {
		return this.orderby;
	}

	public void setOrderby(BigDecimal orderby) {
		this.orderby = orderby;
	}

	@Column(name = "required", length = 1)
	public String getRequired() {
		return this.required;
	}

	public void setRequired(String required) {
		this.required = required;
	}

	@Column(name = "created_by_default", length = 1)
	public String getCreatedByDefault() {
		return this.createdByDefault;
	}

	public void setCreatedByDefault(String createdByDefault) {
		this.createdByDefault = createdByDefault;
	}

}
