package entity.document;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "document", schema = "public")
public class Document implements java.io.Serializable {

	private BigDecimal document;
	private String docNr;
	private String name;
	private String description;
	private Date created;
	private BigDecimal createdBy;
	private Date updated;
	private BigDecimal updatedBy;
	private BigDecimal docStatusTypeFk;
	private String filename;

	public Document() {
	}

	public Document(BigDecimal document) {
		this.document = document;
	}

	public Document(BigDecimal document, String docNr, String name, String description, Date created, BigDecimal createdBy, Date updated, BigDecimal updatedBy, BigDecimal docStatusTypeFk,
			String filename) {
		this.document = document;
		this.docNr = docNr;
		this.name = name;
		this.description = description;
		this.created = created;
		this.createdBy = createdBy;
		this.updated = updated;
		this.updatedBy = updatedBy;
		this.docStatusTypeFk = docStatusTypeFk;
		this.filename = filename;
	}

	@Id
	@Column(name = "document", precision = 10, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public BigDecimal getDocument() {
		return this.document;
	}

	public void setDocument(BigDecimal document) {
		this.document = document;
	}

	@Column(name = "doc_nr")
	public String getDocNr() {
		return this.docNr;
	}

	public void setDocNr(String docNr) {
		this.docNr = docNr;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", precision = 10, scale = 0)
	public BigDecimal getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(BigDecimal createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "updated_by", precision = 10, scale = 0)
	public BigDecimal getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(BigDecimal updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "doc_status_type_fk", precision = 10, scale = 0)
	public BigDecimal getDocStatusTypeFk() {
		return this.docStatusTypeFk;
	}

	public void setDocStatusTypeFk(BigDecimal docStatusTypeFk) {
		this.docStatusTypeFk = docStatusTypeFk;
	}

	@Column(name = "filename")
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Override
	public String toString() {
		return "Document [document=" + document + ", docNr=" + docNr + ", name=" + name + ", description=" + description + ", created=" + created + ", createdBy=" + createdBy + ", updated=" + updated
				+ ", updatedBy=" + updatedBy + ", docStatusTypeFk=" + docStatusTypeFk + ", filename=" + filename + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((document == null) ? 0 : document.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Document other = (Document) obj;
		if (document == null) {
			if (other.document != null)
				return false;
		} else if (!document.equals(other.document))
			return false;
		return true;
	}

}
