package entity.document;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocumentDocCatalog generated by hbm2java
 */
@Entity
@Table(name = "document_doc_catalog", schema = "public")
public class DocumentDocCatalog implements java.io.Serializable {

	private BigDecimal documentDocCatalog;
	private BigDecimal documentFk;
	private BigDecimal docCatalogFk;
	private Date catalogTime;

	public DocumentDocCatalog() {
	}

	public DocumentDocCatalog(BigDecimal documentDocCatalog) {
		this.documentDocCatalog = documentDocCatalog;
	}

	public DocumentDocCatalog(BigDecimal documentDocCatalog, BigDecimal documentFk, BigDecimal docCatalogFk, Date catalogTime) {
		this.documentDocCatalog = documentDocCatalog;
		this.documentFk = documentFk;
		this.docCatalogFk = docCatalogFk;
		this.catalogTime = catalogTime;
	}

	@Id
	@Column(name = "document_doc_catalog", unique = true, nullable = false, precision = 10, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public BigDecimal getDocumentDocCatalog() {
		return this.documentDocCatalog;
	}

	public void setDocumentDocCatalog(BigDecimal documentDocCatalog) {
		this.documentDocCatalog = documentDocCatalog;
	}

	@Column(name = "document_fk", precision = 10, scale = 0)
	public BigDecimal getDocumentFk() {
		return this.documentFk;
	}

	public void setDocumentFk(BigDecimal documentFk) {
		this.documentFk = documentFk;
	}

	@Column(name = "doc_catalog_fk", precision = 10, scale = 0)
	public BigDecimal getDocCatalogFk() {
		return this.docCatalogFk;
	}

	public void setDocCatalogFk(BigDecimal docCatalogFk) {
		this.docCatalogFk = docCatalogFk;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "catalog_time", length = 29)
	public Date getCatalogTime() {
		return this.catalogTime;
	}

	public void setCatalogTime(Date catalogTime) {
		this.catalogTime = catalogTime;
	}

}
