package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", schema = "public")
public class Address implements java.io.Serializable {

	private BigDecimal address;
	private BigDecimal addressTypeFk;
	private BigDecimal subjectFk;
	private BigDecimal subjectTypeFk;
	private String country;
	private String county;
	private String townVillage;
	private String streetAddress;
	private String zipcode;

	public Address() {
	}

	public Address(BigDecimal address) {
		this.address = address;
	}

	public Address(BigDecimal address, BigDecimal addressTypeFk, BigDecimal subjectFk, BigDecimal subjectTypeFk, String country, String county, String townVillage, String streetAddress, String zipcode) {
		this.address = address;
		this.addressTypeFk = addressTypeFk;
		this.subjectFk = subjectFk;
		this.subjectTypeFk = subjectTypeFk;
		this.country = country;
		this.county = county;
		this.townVillage = townVillage;
		this.streetAddress = streetAddress;
		this.zipcode = zipcode;
	}

	@Id
	@Column(name = "address", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getAddress() {
		return this.address;
	}

	public void setAddress(BigDecimal address) {
		this.address = address;
	}

	@Column(name = "address_type_fk", precision = 10, scale = 0)
	public BigDecimal getAddressTypeFk() {
		return this.addressTypeFk;
	}

	public void setAddressTypeFk(BigDecimal addressTypeFk) {
		this.addressTypeFk = addressTypeFk;
	}

	@Column(name = "subject_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectFk() {
		return this.subjectFk;
	}

	public void setSubjectFk(BigDecimal subjectFk) {
		this.subjectFk = subjectFk;
	}

	@Column(name = "subject_type_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectTypeFk() {
		return this.subjectTypeFk;
	}

	public void setSubjectTypeFk(BigDecimal subjectTypeFk) {
		this.subjectTypeFk = subjectTypeFk;
	}

	@Column(name = "country", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "county", length = 100)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "town_village", length = 100)
	public String getTownVillage() {
		return this.townVillage;
	}

	public void setTownVillage(String townVillage) {
		this.townVillage = townVillage;
	}

	@Column(name = "street_address", length = 100)
	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	@Column(name = "zipcode", length = 50)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

}
