package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact", schema = "public")
public class Contact implements java.io.Serializable {

	private BigDecimal contact;
	private BigDecimal subjectFk;
	private BigDecimal contactTypeFk;
	private String valueText;
	private BigDecimal orderby;
	private BigDecimal subjectTypeFk;
	private String note;

	public Contact() {
	}

	public Contact(BigDecimal contact) {
		this.contact = contact;
	}

	public Contact(BigDecimal contact, BigDecimal subjectFk, BigDecimal contactTypeFk, String valueText, BigDecimal orderby, BigDecimal subjectTypeFk, String note) {
		this.contact = contact;
		this.subjectFk = subjectFk;
		this.contactTypeFk = contactTypeFk;
		this.valueText = valueText;
		this.orderby = orderby;
		this.subjectTypeFk = subjectTypeFk;
		this.note = note;
	}

	@Id
	@Column(name = "contact", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getContact() {
		return this.contact;
	}

	public void setContact(BigDecimal contact) {
		this.contact = contact;
	}

	@Column(name = "subject_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectFk() {
		return this.subjectFk;
	}

	public void setSubjectFk(BigDecimal subjectFk) {
		this.subjectFk = subjectFk;
	}

	@Column(name = "contact_type_fk", precision = 10, scale = 0)
	public BigDecimal getContactTypeFk() {
		return this.contactTypeFk;
	}

	public void setContactTypeFk(BigDecimal contactTypeFk) {
		this.contactTypeFk = contactTypeFk;
	}

	@Column(name = "value_text")
	public String getValueText() {
		return this.valueText;
	}

	public void setValueText(String valueText) {
		this.valueText = valueText;
	}

	@Column(name = "orderby", precision = 10, scale = 0)
	public BigDecimal getOrderby() {
		return this.orderby;
	}

	public void setOrderby(BigDecimal orderby) {
		this.orderby = orderby;
	}

	@Column(name = "subject_type_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectTypeFk() {
		return this.subjectTypeFk;
	}

	public void setSubjectTypeFk(BigDecimal subjectTypeFk) {
		this.subjectTypeFk = subjectTypeFk;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
