package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ContactType generated by hbm2java
 */
@Entity
@Table(name = "contact_type", schema = "public")
public class ContactType implements java.io.Serializable {

	private BigDecimal contactType;
	private String typeName;

	public ContactType() {
	}

	public ContactType(BigDecimal contactType) {
		this.contactType = contactType;
	}

	public ContactType(BigDecimal contactType, String typeName) {
		this.contactType = contactType;
		this.typeName = typeName;
	}

	@Id
	@Column(name = "contact_type", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getContactType() {
		return this.contactType;
	}

	public void setContactType(BigDecimal contactType) {
		this.contactType = contactType;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
