package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", schema = "public")
public class Customer implements java.io.Serializable {

	private BigDecimal customer;
	private BigDecimal subjectFk;
	private BigDecimal subjectTypeFk;

	public Customer() {
	}

	public Customer(BigDecimal customer) {
		this.customer = customer;
	}

	public Customer(BigDecimal customer, BigDecimal subjectFk, BigDecimal subjectTypeFk) {
		this.customer = customer;
		this.subjectFk = subjectFk;
		this.subjectTypeFk = subjectTypeFk;
	}

	@Id
	@Column(name = "customer", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getCustomer() {
		return this.customer;
	}

	public void setCustomer(BigDecimal customer) {
		this.customer = customer;
	}

	@Column(name = "subject_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectFk() {
		return this.subjectFk;
	}

	public void setSubjectFk(BigDecimal subjectFk) {
		this.subjectFk = subjectFk;
	}

	@Column(name = "subject_type_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectTypeFk() {
		return this.subjectTypeFk;
	}

	public void setSubjectTypeFk(BigDecimal subjectTypeFk) {
		this.subjectTypeFk = subjectTypeFk;
	}

}
