package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeRole generated by hbm2java
 */
@Entity
@Table(name = "employee_role", schema = "public")
public class EmployeeRole implements java.io.Serializable {

	private BigDecimal employeeRole;
	private BigDecimal employeeFk;
	private BigDecimal employeeRoleTypeFk;
	private String active;

	public EmployeeRole() {
	}

	public EmployeeRole(BigDecimal employeeRole) {
		this.employeeRole = employeeRole;
	}

	public EmployeeRole(BigDecimal employeeRole, BigDecimal employeeFk, BigDecimal employeeRoleTypeFk, String active) {
		this.employeeRole = employeeRole;
		this.employeeFk = employeeFk;
		this.employeeRoleTypeFk = employeeRoleTypeFk;
		this.active = active;
	}

	@Id
	@Column(name = "employee_role", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getEmployeeRole() {
		return this.employeeRole;
	}

	public void setEmployeeRole(BigDecimal employeeRole) {
		this.employeeRole = employeeRole;
	}

	@Column(name = "employee_fk", precision = 10, scale = 0)
	public BigDecimal getEmployeeFk() {
		return this.employeeFk;
	}

	public void setEmployeeFk(BigDecimal employeeFk) {
		this.employeeFk = employeeFk;
	}

	@Column(name = "employee_role_type_fk", precision = 10, scale = 0)
	public BigDecimal getEmployeeRoleTypeFk() {
		return this.employeeRoleTypeFk;
	}

	public void setEmployeeRoleTypeFk(BigDecimal employeeRoleTypeFk) {
		this.employeeRoleTypeFk = employeeRoleTypeFk;
	}

	@Column(name = "active", length = 1)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

}
