package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeRoleType generated by hbm2java
 */
@Entity
@Table(name = "employee_role_type", schema = "public")
public class EmployeeRoleType implements java.io.Serializable {

	private BigDecimal employeeRoleType;
	private String typeName;

	public EmployeeRoleType() {
	}

	public EmployeeRoleType(BigDecimal employeeRoleType) {
		this.employeeRoleType = employeeRoleType;
	}

	public EmployeeRoleType(BigDecimal employeeRoleType, String typeName) {
		this.employeeRoleType = employeeRoleType;
		this.typeName = typeName;
	}

	@Id
	@Column(name = "employee_role_type", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getEmployeeRoleType() {
		return this.employeeRoleType;
	}

	public void setEmployeeRoleType(BigDecimal employeeRoleType) {
		this.employeeRoleType = employeeRoleType;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
