package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EntPerRelationType generated by hbm2java
 */
@Entity
@Table(name = "ent_per_relation_type", schema = "public")
public class EntPerRelationType implements java.io.Serializable {

	private BigDecimal entPerRelationType;
	private String typeName;

	public EntPerRelationType() {
	}

	public EntPerRelationType(BigDecimal entPerRelationType) {
		this.entPerRelationType = entPerRelationType;
	}

	public EntPerRelationType(BigDecimal entPerRelationType, String typeName) {
		this.entPerRelationType = entPerRelationType;
		this.typeName = typeName;
	}

	@Id
	@Column(name = "ent_per_relation_type", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getEntPerRelationType() {
		return this.entPerRelationType;
	}

	public void setEntPerRelationType(BigDecimal entPerRelationType) {
		this.entPerRelationType = entPerRelationType;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
