package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StructUnit generated by hbm2java
 */
@Entity
@Table(name = "struct_unit", schema = "public")
public class StructUnit implements java.io.Serializable {

	private BigDecimal structUnit;
	private BigDecimal enterpriseFk;
	private BigDecimal upperUnitFk;
	private BigDecimal level;
	private String name;

	public StructUnit() {
	}

	public StructUnit(BigDecimal structUnit) {
		this.structUnit = structUnit;
	}

	public StructUnit(BigDecimal structUnit, BigDecimal enterpriseFk, BigDecimal upperUnitFk, BigDecimal level, String name) {
		this.structUnit = structUnit;
		this.enterpriseFk = enterpriseFk;
		this.upperUnitFk = upperUnitFk;
		this.level = level;
		this.name = name;
	}

	@Id
	@Column(name = "struct_unit", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getStructUnit() {
		return this.structUnit;
	}

	public void setStructUnit(BigDecimal structUnit) {
		this.structUnit = structUnit;
	}

	@Column(name = "enterprise_fk", precision = 10, scale = 0)
	public BigDecimal getEnterpriseFk() {
		return this.enterpriseFk;
	}

	public void setEnterpriseFk(BigDecimal enterpriseFk) {
		this.enterpriseFk = enterpriseFk;
	}

	@Column(name = "upper_unit_fk", precision = 10, scale = 0)
	public BigDecimal getUpperUnitFk() {
		return this.upperUnitFk;
	}

	public void setUpperUnitFk(BigDecimal upperUnitFk) {
		this.upperUnitFk = upperUnitFk;
	}

	@Column(name = "level", precision = 10, scale = 0)
	public BigDecimal getLevel() {
		return this.level;
	}

	public void setLevel(BigDecimal level) {
		this.level = level;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
