package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubjectType generated by hbm2java
 */
@Entity
@Table(name = "subject_type", schema = "public")
public class SubjectType implements java.io.Serializable {

	private BigDecimal subjectType;
	private String typeName;

	public SubjectType() {
	}

	public SubjectType(BigDecimal subjectType) {
		this.subjectType = subjectType;
	}

	public SubjectType(BigDecimal subjectType, String typeName) {
		this.subjectType = subjectType;
		this.typeName = typeName;
	}

	@Id
	@Column(name = "subject_type", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getSubjectType() {
		return this.subjectType;
	}

	public void setSubjectType(BigDecimal subjectType) {
		this.subjectType = subjectType;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
