package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubjectAttribute generated by hbm2java
 */
@Entity
@Table(name = "subject_attribute", schema = "public")
public class SubjectAttribute implements java.io.Serializable {

	private BigDecimal subjectAttribute;
	private BigDecimal subjectFk;
	private BigDecimal subjectAttributeTypeFk;
	private BigDecimal subjectTypeFk;
	private BigDecimal orderby;
	private String valueText;
	private BigDecimal valueNumber;
	private Date valueDate;
	private BigDecimal dataType;

	public SubjectAttribute() {
	}

	public SubjectAttribute(BigDecimal subjectAttribute) {
		this.subjectAttribute = subjectAttribute;
	}

	public SubjectAttribute(BigDecimal subjectAttribute, BigDecimal subjectFk, BigDecimal subjectAttributeTypeFk, BigDecimal subjectTypeFk, BigDecimal orderby, String valueText,
			BigDecimal valueNumber, Date valueDate, BigDecimal dataType) {
		this.subjectAttribute = subjectAttribute;
		this.subjectFk = subjectFk;
		this.subjectAttributeTypeFk = subjectAttributeTypeFk;
		this.subjectTypeFk = subjectTypeFk;
		this.orderby = orderby;
		this.valueText = valueText;
		this.valueNumber = valueNumber;
		this.valueDate = valueDate;
		this.dataType = dataType;
	}

	@Id
	@Column(name = "subject_attribute", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getSubjectAttribute() {
		return this.subjectAttribute;
	}

	public void setSubjectAttribute(BigDecimal subjectAttribute) {
		this.subjectAttribute = subjectAttribute;
	}

	@Column(name = "subject_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectFk() {
		return this.subjectFk;
	}

	public void setSubjectFk(BigDecimal subjectFk) {
		this.subjectFk = subjectFk;
	}

	@Column(name = "subject_attribute_type_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectAttributeTypeFk() {
		return this.subjectAttributeTypeFk;
	}

	public void setSubjectAttributeTypeFk(BigDecimal subjectAttributeTypeFk) {
		this.subjectAttributeTypeFk = subjectAttributeTypeFk;
	}

	@Column(name = "subject_type_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectTypeFk() {
		return this.subjectTypeFk;
	}

	public void setSubjectTypeFk(BigDecimal subjectTypeFk) {
		this.subjectTypeFk = subjectTypeFk;
	}

	@Column(name = "orderby", precision = 10, scale = 0)
	public BigDecimal getOrderby() {
		return this.orderby;
	}

	public void setOrderby(BigDecimal orderby) {
		this.orderby = orderby;
	}

	@Column(name = "value_text")
	public String getValueText() {
		return this.valueText;
	}

	public void setValueText(String valueText) {
		this.valueText = valueText;
	}

	@Column(name = "value_number", precision = 131089, scale = 0)
	public BigDecimal getValueNumber() {
		return this.valueNumber;
	}

	public void setValueNumber(BigDecimal valueNumber) {
		this.valueNumber = valueNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "value_date", length = 13)
	public Date getValueDate() {
		return this.valueDate;
	}

	public void setValueDate(Date valueDate) {
		this.valueDate = valueDate;
	}

	@Column(name = "data_type", precision = 1, scale = 0)
	public BigDecimal getDataType() {
		return this.dataType;
	}

	public void setDataType(BigDecimal dataType) {
		this.dataType = dataType;
	}

}
