package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubjectAttributeType generated by hbm2java
 */
@Entity
@Table(name = "subject_attribute_type", schema = "public")
public class SubjectAttributeType implements java.io.Serializable {

	private BigDecimal subjectAttributeType;
	private BigDecimal subjectTypeFk;
	private String typeName;
	private BigDecimal dataType;
	private BigDecimal orderby;
	private String required;
	private String multipleAttributes;
	private String createdByDefault;

	public SubjectAttributeType() {
	}

	public SubjectAttributeType(BigDecimal subjectAttributeType) {
		this.subjectAttributeType = subjectAttributeType;
	}

	public SubjectAttributeType(BigDecimal subjectAttributeType, BigDecimal subjectTypeFk, String typeName, BigDecimal dataType, BigDecimal orderby, String required, String multipleAttributes,
			String createdByDefault) {
		this.subjectAttributeType = subjectAttributeType;
		this.subjectTypeFk = subjectTypeFk;
		this.typeName = typeName;
		this.dataType = dataType;
		this.orderby = orderby;
		this.required = required;
		this.multipleAttributes = multipleAttributes;
		this.createdByDefault = createdByDefault;
	}

	@Id
	@Column(name = "subject_attribute_type", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getSubjectAttributeType() {
		return this.subjectAttributeType;
	}

	public void setSubjectAttributeType(BigDecimal subjectAttributeType) {
		this.subjectAttributeType = subjectAttributeType;
	}

	@Column(name = "subject_type_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectTypeFk() {
		return this.subjectTypeFk;
	}

	public void setSubjectTypeFk(BigDecimal subjectTypeFk) {
		this.subjectTypeFk = subjectTypeFk;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "data_type", precision = 1, scale = 0)
	public BigDecimal getDataType() {
		return this.dataType;
	}

	public void setDataType(BigDecimal dataType) {
		this.dataType = dataType;
	}

	@Column(name = "orderby", precision = 10, scale = 0)
	public BigDecimal getOrderby() {
		return this.orderby;
	}

	public void setOrderby(BigDecimal orderby) {
		this.orderby = orderby;
	}

	@Column(name = "required", length = 1)
	public String getRequired() {
		return this.required;
	}

	public void setRequired(String required) {
		this.required = required;
	}

	@Column(name = "multiple_attributes", length = 1)
	public String getMultipleAttributes() {
		return this.multipleAttributes;
	}

	public void setMultipleAttributes(String multipleAttributes) {
		this.multipleAttributes = multipleAttributes;
	}

	@Column(name = "created_by_default", length = 1)
	public String getCreatedByDefault() {
		return this.createdByDefault;
	}

	public void setCreatedByDefault(String createdByDefault) {
		this.createdByDefault = createdByDefault;
	}

}
