package entity.subject;

// Generated May 23, 2015 1:59:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserAccount generated by hbm2java
 */
@Entity
@Table(name = "user_account", schema = "public")
public class UserAccount implements java.io.Serializable {

	private BigDecimal userAccount;
	private BigDecimal subjectTypeFk;
	private BigDecimal subjectFk;
	private String username;
	private String passw;
	private BigDecimal status;
	private Date validFrom;
	private Date validTo;
	private BigDecimal createdBy;
	private Date created;
	private String passwordNeverExpires;

	public UserAccount() {
	}

	public UserAccount(BigDecimal userAccount) {
		this.userAccount = userAccount;
	}

	public UserAccount(BigDecimal userAccount, BigDecimal subjectTypeFk, BigDecimal subjectFk, String username, String passw, BigDecimal status, Date validFrom, Date validTo, BigDecimal createdBy,
			Date created, String passwordNeverExpires) {
		this.userAccount = userAccount;
		this.subjectTypeFk = subjectTypeFk;
		this.subjectFk = subjectFk;
		this.username = username;
		this.passw = passw;
		this.status = status;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.createdBy = createdBy;
		this.created = created;
		this.passwordNeverExpires = passwordNeverExpires;
	}

	@Id
	@Column(name = "user_account", unique = true, nullable = false, precision = 10, scale = 0)
	public BigDecimal getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(BigDecimal userAccount) {
		this.userAccount = userAccount;
	}

	@Column(name = "subject_type_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectTypeFk() {
		return this.subjectTypeFk;
	}

	public void setSubjectTypeFk(BigDecimal subjectTypeFk) {
		this.subjectTypeFk = subjectTypeFk;
	}

	@Column(name = "subject_fk", precision = 10, scale = 0)
	public BigDecimal getSubjectFk() {
		return this.subjectFk;
	}

	public void setSubjectFk(BigDecimal subjectFk) {
		this.subjectFk = subjectFk;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "passw", length = 300)
	public String getPassw() {
		return this.passw;
	}

	public void setPassw(String passw) {
		this.passw = passw;
	}

	@Column(name = "status", precision = 10, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_from", length = 13)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_to", length = 13)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	@Column(name = "created_by", precision = 10, scale = 0)
	public BigDecimal getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(BigDecimal createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "password_never_expires", length = 1)
	public String getPasswordNeverExpires() {
		return this.passwordNeverExpires;
	}

	public void setPasswordNeverExpires(String passwordNeverExpires) {
		this.passwordNeverExpires = passwordNeverExpires;
	}

}
